# Generated by Django 5.0.1 on 2024-01-29 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('W2', '0002_alter_present_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='present',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
